kind: pipeline
name: default

workspace:
  base: /go
  path: src/github.com/iot-my-world/brain

services:
  - name: db
    image: mongo

steps:
  - name: build
    image: golang
    commands:
      - cd start
      - go get
      - cd ../build
      - env GOOD=linux GOARCH=amd64 go build -o=brain /go/src/github.com/iot-my-world/brain/start

  - name: test
    image: centos
    commands:
      - cd ../build
      - ./brain -mongoNodes=db:27016

  - name: deploy
    image: centos
    environment:
      SSH_PRIVATE_KEY:
        from_secret: ssh_pvt_key
      $SSH_KNOWN_HOSTS:
        from_secret: ssh_known_hosts
    commands:
      # Install ssh-agent if not already installed this is required by Docker
      - 'which || yum -y install which'
      - 'which ssh-agent || yum -y install openssh openssh-clients '

      # Run ssh-agent (inside the build environment)
      - eval $(ssh-agent -s)

        # Add the SSH key stored in SSH_PRIVATE_KEY variable to the agent store
      # We're using tr to fix line endings which makes ed25519 keys work
      # without extra base64 encoding
      - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null

      # Create the SSH directory and give it the right permissions
      - mkdir -p ~/.ssh
      - chmod 700 ~/.ssh

      # update known hosts
      - echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
      - chmod 644 ~/.ssh/known_hosts

trigger:
  branch:
    - master
  event:
    - push
