version: '2'
services:
  iotzookeeper:
    container_name: iotTracker-zookeeper
    image: wurstmeister/zookeeper
    ports:
    - "2182:2182"
  iotkafka:
    container_name: iotTracker-kafka
    image: wurstmeister/kafka
    ports:
    - "9093:9093"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: iotzookeeper:2182
      KAFKA_CREATE_TOPICS: "brainQueue:1:3"
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock